[功能開發] game chat component layout
Game-as-a-Service/IncanGold pull request #11
Opened 2023-06-16 17:13 UTC by frohman-chang

### 基本聊天室 layout

by @GinaHsin 

push by @frohman-chang

2023-06-17 01:47 UTC, JohnsonMao approved these changes

2023-06-17 01:47 UTC, JohnsonMao commented on frontend/components/game-chat.vue
> +	padding: 0 10px 10px 20px;
強迫症表示看到這個排版有點難受XDD

2023-06-17 03:56 UTC, Peg-L commented
input
* 送出 icon 使用背景圖 ➡️ 改為按鈕
* 字體顏色 ➡️  改為白
* ➡️ 加上 padding-left: 15px; 讓字不要太黏邊框
* ➡️ margin-top: 10px;

2023-06-17 04:02 UTC, Peg-L commented on frontend/components/game-chat.vue
> +	padding: 0 10px 10px 20px;
我覺得可以 
padding: 10px 10px 10px 20px;

2023-06-18 04:24 UTC, frohman-chang commented on frontend/components/game-chat.vue
> +	padding: 0 10px 10px 20px;
給點尊重~
畫面上要長得像設計稿優先 XD

2023-06-18 06:57 UTC, JohnsonMao requested changes

2023-06-18 06:57 UTC, JohnsonMao commented on packages/incan-gold-core/dist/entities/Bag.js
需要移除 dist

2023-09-06 13:49 UTC, merged