modified: login & signup layout
Game-as-a-Service/IncanGold pull request #34
Opened 2023-09-16 18:20 UTC by Peg-L

微調版面
* input 加一點 padding
* 元素之間的距離
* social btns 圖片更新
* 其他小地方

2023-09-17 06:56 UTC, frohman-chang requested changes
safari 與 firefox 無法顯示小於 1px 高寬

2023-09-17 06:56 UTC, frohman-chang commented on frontend/components/form/divide.vue
> +  height: 0.25px;
有些瀏覽器無法顯示小於 1px 的寬高

![Screenshot 2023-09-17 at 2 50 03 PM](https://github.com/Game-as-a-Service/IncanGold/assets/126720593/fdd7223f-bbad-4136-880d-5ff020b8a960)

2023-09-23 02:39 UTC, Peg-L commented on frontend/components/form/divide.vue
> +  height: 0.25px;
@frohman-chang 0.25px 問題 修改完成

2023-10-17 11:04 UTC, frohman-chang approved these changes
GJ

2023-10-17 11:04 UTC, merged